language: go

go:
  - 1.6

go_import_path: github.com/raininfall/gorx

install:
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert
  - go get github.com/eapache/channels

script: goveralls -service travis-ci -repotoken $COVERALLS_TOKEN
